image: cmacmackin/fortran-env:ubuntu-latest

# Build your software, along with all tests
compile:
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=TESTING
    - make
  stage: build
  artifacts:
    paths:
    - build/
    expire_in: 1 week

# Try building documentation, but still run unit tests if fail
build_docs:
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make docs
  stage: build
  artifacts:
    paths:
    - build/docs/
    expire_in: 1 day
  allow_failure: true



# Run unit tests, producing a report on results
unit_tests:
  script:
    - cd build
    - tests/unit_tests -robust -xml pfunit.xml -name UnitTests
    - make gcovr
    - mv gcovr unit_test_coverage
  stage: test
  coverage: '/^lines: (\d+.\d+)%/'
  artifacts:
    paths:
    - build/unit_test_coverage/
    expire_in: 1 week
#   Version of GitLab runner currently available at CCFE does not support this
#   reports:
#     junit: pfunit.xml

# Run all tests, e.g. integration tests, in addition to unit tests
all_tests:
  script:
    - cd build
    - ctest
    - make gcovr
    - mv gcovr all_test_coverage
  stage: test
  coverage: '/^lines: (\d+.\d+)%/'
  artifacts:
    paths:
    - build/all_test_coverage/
    expire_in: 1 week

# Test that cmake installs everything correctly so that programs can
# be executed and libraries linked to
install_test:
  script:
    - cd build
    - make install
    # Ensure that the program has installed in the PATH and runs
    - which projectname
    - projectname
    # Try using these libraries in another cmake project
    - cd tests/test_installation
    - cmake .
    - make
    - ./test_program
  stage: test


# Deploy documentation and code coverage reports to GitLab pages
pages:
  script:
    - mv build/docs public
    - mv build/unit_test_coverage public/unit_coverage
    - mv build/all_test_coverage public/all_coverage
  stage: deploy
  dependencies:
    - build_docs
    - unit_tests
    - all_tests
  artifacts:
    paths:
    - public/
  only:
    - master
